title: Desbroce de Fincas en Pontevedra | Poda y Limpieza de Montes
description: Empresa especializada en desbroce de fincas, limpieza de montes, poda de árboles y mantenimiento de jardines. Servicio profesional en toda Pontevedra con maquinaria.

url: "https://desbroces-pontevedra.fun"  # ✅ Tu dominio real

color-scheme: "mediumseagreen"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

