apiVersion: apps/v1
kind: Deployment
metadata:
  name: desbroces-jekyll
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desbroces-jekyll
  template:
    metadata:
      labels:
        app: desbroces-jekyll
    spec:
      containers:
      - name: jekyll-site
        image: gcr.io/useful-memory-464107-d6/desbroces-pontevedra-site
        ports:
        - containerPort: 8080
