apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: desbroces-cluster
  git:
    syncRepo: "https://github.com/Very-lcuky/desbroces-pontevedra-site.git"
    syncBranch: "main"
    policyDir: "k8s-configs"
    secretType: none
  preventDrift: true
